
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-04T09:07:36+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "54ed067e24e1f8a5fc00a38a05410e5f3466e625",
 "version": "3.0.73"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
